version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  # Volitelné služby
  backend:
    profiles: ["backend"]
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=firesphere
      - DB_PORT=5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    profiles: ["backend"]
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=firesphere
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 
