server {
    listen 80; # Naslouchá na portu 80 na všech IP adresách
    server_name localhost; # Název serveru (může být upraven podle potřeby)

    location / {
        root /usr/share/nginx/html; # Cesta k souborům, které server poskytuje
        index index.html; # Výchozí soubor, který se načte
        try_files $uri $uri/ /index.html; # Zajištění, že požadavky směřují na index.html
    }
}

    # Proxy pro API požadavky
    #    location /api {
    #   proxy_pass http://backend:3001;
    #    proxy_http_version 1.1;
    #   proxy_set_header Upgrade $http_upgrade;
    #   proxy_set_header Connection 'upgrade';
    #   proxy_set_header Host $host;
    #   proxy_cache_bypass $http_upgrade;
    #}
    #} 
